/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2023-09-24 17:46:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.java.infinite.LeaveDetailsDAO;
import com.java.infinite.LeaveDetailsDAOImpl;
import com.java.infinite.LeaveType;
import java.util.Date;
import com.java.infinite.LeaveDetails;
import java.text.SimpleDateFormat;

public final class ApplyLeave_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.java.infinite.LeaveDetails");
    _jspx_imports_classes.add("com.java.infinite.LeaveType");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("com.java.infinite.LeaveDetailsDAO");
    _jspx_imports_classes.add("com.java.infinite.LeaveDetailsDAOImpl");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Leave Application Form</title>\r\n");
      out.write("<style>\r\n");
      out.write("    /* Remove border from table and form elements */\r\n");
      out.write("    table, th, td {\r\n");
      out.write("        border: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("        background-color: #f2f2f2; /* Light Gray */\r\n");
      out.write("        font-family: Arial, sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Stylish form container */\r\n");
      out.write("    .form-container {\r\n");
      out.write("        background-color: #fff; /* White */\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        margin: 20px auto;\r\n");
      out.write("        width: 60%;\r\n");
      out.write("        max-width: 600px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h1 {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        color: #333; /* Dark Gray */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Stylish form elements */\r\n");
      out.write("    input[type=\"text\"], select {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding: 12px;\r\n");
      out.write("        margin: 5px 0;\r\n");
      out.write("        border: 1px solid #ccc;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input[type=\"text\"]:focus, select:focus {\r\n");
      out.write("        border-color: #007bff; /* Blue on focus */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    label {\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Stylish submit button */\r\n");
      out.write("    input[type=\"submit\"] {\r\n");
      out.write("        background-color: #007bff; /* Blue */\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("        padding: 12px 20px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        transition: background-color 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input[type=\"submit\"]:hover {\r\n");
      out.write("        background-color: #0056b3; /* Darker Blue on hover */\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

int empId = (int)session.getAttribute("empId");

      out.write("\r\n");
      out.write("    <center>\r\n");
      out.write("        <h1>Leave Application Form</h1>\r\n");
      out.write("        <form action=\"ApplyLeaveMain.jsp\" method=\"post\">\r\n");
      out.write("            <table>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td><label for=\"emp_id\">Employee ID:</label></td>\r\n");
      out.write("                    <td><input type=\"text\" name=\"emp_id\" value=\"");
      out.print(empId);
      out.write("\" readonly></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td><label for=\"leave_start_date\">Leave Start Date (yyyy-MM-dd):</label></td>\r\n");
      out.write("                    <td><input type=\"text\" id=\"leave_start_date\" name=\"leave_start_date\" required></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td><label for=\"leave_end_date\">Leave End Date (yyyy-MM-dd):</label></td>\r\n");
      out.write("                    <td><input type=\"text\" id=\"leave_end_date\" name=\"leave_end_date\" required></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td><label for=\"leave_type\">Leave Type:</label></td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <select id=\"leave_type\" name=\"leave_type\" required>\r\n");
      out.write("                            <option value=\"EL\">EL (Earned Leave)</option>\r\n");
      out.write("                            <option value=\"PL\">PL (Paid Leave)</option>\r\n");
      out.write("                            <option value=\"ML\">ML (Maternity Leave)</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td><label for=\"leave_reason\">Leave Reason:</label></td>\r\n");
      out.write("                    <td><input type=\"text\" id=\"leave_reason\" name=\"leave_reason\" required></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            <br>\r\n");
      out.write("            <input type=\"submit\" value=\"Submit\">\r\n");
      out.write("        </form>\r\n");
      out.write("    </center>\r\n");

    if (request.getParameter("emp_id")!=null && request.getParameter("leave_start_date")!=null){
    
    String leaveStartDate = request.getParameter("leave_start_date");
    String leaveEndDate = request.getParameter("leave_end_date");
    String leaveType = request.getParameter("leave_type");
    String leaveReason = request.getParameter("leave_reason");
    
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    LeaveDetails leavedetails = new LeaveDetails();
    
    Date startDate = sdf.parse(leaveStartDate);
    java.sql.Date sqlStartDate = new java.sql.Date(startDate.getTime());
    
    java.util.Date endDate = sdf.parse(leaveEndDate);
    java.sql.Date sqlEndDate = new java.sql.Date(endDate.getTime());
    
    leavedetails.setEmpId(empId);
    leavedetails.setLeaveStartDate(sqlStartDate);
    leavedetails.setLeaveEndDate(sqlEndDate);
    leavedetails.setLeaveType(LeaveType.valueOf(leaveType));
    leavedetails.setLeaveReason(leaveReason);
    
    LeaveDetailsDAO dao = new LeaveDetailsDAOImpl();
    out.println(dao.applyLeave(leavedetails));
    
    
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "EmployShow.jsp", out, false);
      out.write("\r\n");
      out.write("    ");

    }

      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
