/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2023-09-23 10:41:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.java.infinite.Employee;
import com.java.infinite.EmployeeDAOImpl;
import com.java.infinite.EmployeeDAO;
import com.java.infinite.LeaveDetails;
import com.java.infinite.LeaveDetailsDAOImpl;
import com.java.infinite.LeaveDetailsDAO;

public final class ApproveDenyNew_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.java.infinite.LeaveDetails");
    _jspx_imports_classes.add("com.java.infinite.Employee");
    _jspx_imports_classes.add("com.java.infinite.EmployeeDAOImpl");
    _jspx_imports_classes.add("com.java.infinite.LeaveDetailsDAOImpl");
    _jspx_imports_classes.add("com.java.infinite.LeaveDetailsDAO");
    _jspx_imports_classes.add("com.java.infinite.EmployeeDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	
	if (request.getParameter("leaveId")!=null) {
		 int leaveId = Integer.parseInt(request.getParameter("leaveId"));
		 session.setAttribute("leaveId", request.getParameter("leaveId"));
	}
//	out.println(leaveId);
	String id = (String)session.getAttribute("leaveId");
	int leId = Integer.parseInt(id);
	LeaveDetailsDAO dao = new LeaveDetailsDAOImpl();
	LeaveDetails leave = dao.searchLeaveDao(leId);
	int empId = leave.getEmpId();
	EmployeeDAO edao = new EmployeeDAOImpl();
	Employee employee = edao.searchEmployeeDao(empId);
	

      out.write("\r\n");
      out.write("\t<center>\r\n");
      out.write("\t<form action=\"ApproveDenyNew.jsp\" method=\"post\">\r\n");
      out.write("\t\tLeave Id : ");
      out.print(leave.getLeaveId() );
      out.write(" <Br/>\r\n");
      out.write("\t\tEmployee Id : ");
      out.print(empId );
      out.write(" <br/>\r\n");
      out.write("\t\tEmployee Name : ");
      out.print(employee.getEmpName() );
      out.write("<br/>\r\n");
      out.write("\t\tLeave Balence :  ");
      out.print(employee.getLeaveAvail() );
      out.write("<br/>\r\n");
      out.write("\t\tStart Date :  ");
      out.print(leave.getLeaveStartDate() );
      out.write(" <br/>\r\n");
      out.write("\t\tEnd Date :  ");
      out.print(leave.getLeaveEndDate() );
      out.write("   <br/>\r\n");
      out.write("\t\tNo Of Days : ");
      out.print(leave.getNoOfDays() );
      out.write("  <br/>\r\n");
      out.write("\t\tLeave Type : ");
      out.print(leave.getLeaveType() );
      out.write("  <br/>\r\n");
      out.write("\t\tReason : ");
      out.print(leave.getLeaveReason() );
      out.write("<br>\r\n");
      out.write("\t\tLeave Status :\r\n");
      out.write("\t\t<select name = \"status\">\r\n");
      out.write("\t\t\t<option value=\"YES\">YES</option>\r\n");
      out.write("\t\t\t<option value=\"NO\">NO</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\tManager Comment : \r\n");
      out.write("\t\t<input type=\"text\" name=\"mgcmt\">\r\n");
      out.write("\t\t<input type=\"submit\" value=\"Submit\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</center>\r\n");
      out.write("\t");

	if(request.getParameter("status")!=null && request.getParameter("mgcmt")!=null){
	//	session.setAttribute("leaveId", leaveId);
	
	String status = request.getParameter("status");
	String mgcmt = request.getParameter("mgcmt");
	
	out.println(dao.ApproveDeny(leave.getLeaveId(), employee.getManagerId(), status, mgcmt));
	}
	
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
