/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2023-11-23 09:54:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AppointmentDetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/HospitalProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp2/wtpwebapps/HospitalProviderModule/WEB-INF/lib/jsf-impl-2.2.14.jar!/META-INF/html_basic.tld", Long.valueOf(1479140598000L));
    _jspx_dependants.put("jar:file:/D:/HospitalProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp2/wtpwebapps/HospitalProviderModule/WEB-INF/lib/jsf-impl-2.2.14.jar!/META-INF/jsf_core.tld", Long.valueOf(1479140578000L));
    _jspx_dependants.put("/WEB-INF/lib/jsf-impl-2.2.14.jar", Long.valueOf(1696481161505L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005fview;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005finputText_0026_005fvalue_005fstyle_005fid_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005fmessages_0026_005fid_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005fform_0026_005fstyleClass;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue_005fstyleClass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005fcommandButton_0026_005fvalue_005fstyleClass_005faction_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ff_005fview = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005finputText_0026_005fvalue_005fstyle_005fid_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005fmessages_0026_005fid_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005fform_0026_005fstyleClass = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue_005fstyleClass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005fcommandButton_0026_005fvalue_005fstyleClass_005faction_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ff_005fview.release();
    _005fjspx_005ftagPool_005fh_005finputText_0026_005fvalue_005fstyle_005fid_005fnobody.release();
    _005fjspx_005ftagPool_005fh_005fmessages_0026_005fid_005fnobody.release();
    _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fh_005fform_0026_005fstyleClass.release();
    _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue_005fstyleClass_005fnobody.release();
    _005fjspx_005ftagPool_005fh_005fcommandButton_0026_005fvalue_005fstyleClass_005faction_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_f_005fview_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_f_005fview_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:view
    com.sun.faces.taglib.jsf_core.ViewTag _jspx_th_f_005fview_005f0 = new com.sun.faces.taglib.jsf_core.ViewTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_f_005fview_005f0);
    try {
      _jspx_th_f_005fview_005f0.setPageContext(_jspx_page_context);
      _jspx_th_f_005fview_005f0.setParent(null);
      _jspx_th_f_005fview_005f0.setJspId("jsp_813251680_0");
      int _jspx_eval_f_005fview_005f0 = _jspx_th_f_005fview_005f0.doStartTag();
      if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_f_005fview_005f0);
        }
        do {
          out.write("\r\n");
          out.write("    <html>\r\n");
          out.write("        <head>\r\n");
          out.write("            <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
          out.write("            <title>JSP Page</title>\r\n");
          out.write("\r\n");
          out.write("            <style>\r\n");
          out.write("                body {\r\n");
          out.write("                    font-family: Arial, sans-serif;\r\n");
          out.write("                    background-color: #BFD7EA;\r\n");
          out.write("                    padding: 0;\r\n");
          out.write("                    text-align: center;\r\n");
          out.write("                }\r\n");
          out.write("                \r\n");
          out.write("                h2 {\r\n");
          out.write("                \tmargin-top: 40px;\r\n");
          out.write("                }\r\n");
          out.write("\r\n");
          out.write("                .form-container {\r\n");
          out.write("                    max-width: 800px;\r\n");
          out.write("                    margin: 0 auto;\r\n");
          out.write("                    background-color: #FEE9E1;\r\n");
          out.write("                    padding: 20px;\r\n");
          out.write("                    border-radius: 5px;\r\n");
          out.write("                    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
          out.write("                    text-align: left;\r\n");
          out.write("                    overflow-x: auto;\r\n");
          out.write("                    display: flex;\r\n");
          out.write("                    flex-direction: column;\r\n");
          out.write("                }\r\n");
          out.write("\r\n");
          out.write("                .custom-button {\r\n");
          out.write("                    color: white;\r\n");
          out.write("                    padding: 10px 15px;\r\n");
          out.write("                    border: none;\r\n");
          out.write("                    border-radius: 5px;\r\n");
          out.write("                    cursor: pointer;\r\n");
          out.write("                    margin-top: 15px;\r\n");
          out.write("                    transition: background-color 0.3s; /* Add smooth transition */\r\n");
          out.write("                }\r\n");
          out.write("\r\n");
          out.write("                /* Go Back button styles */\r\n");
          out.write("                .go-back-button {\r\n");
          out.write("                    background-color: #3498db; /* Default background color */\r\n");
          out.write("                }\r\n");
          out.write("\r\n");
          out.write("                .go-back-button:hover {\r\n");
          out.write("                    background-color: #2980b9; /* Hover background color */\r\n");
          out.write("                }\r\n");
          out.write("\r\n");
          out.write("                /* Confirm button styles */\r\n");
          out.write("                .confirm-button {\r\n");
          out.write("                \tmargin-left: 10px;\r\n");
          out.write("                    background-color: #2ecc71; /* Default background color */\r\n");
          out.write("                }\r\n");
          out.write("\r\n");
          out.write("                .confirm-button:hover {\r\n");
          out.write("                    background-color: #27ae60; /* Hover background color */\r\n");
          out.write("                }\r\n");
          out.write("\r\n");
          out.write("                /* Cancel button styles */\r\n");
          out.write("                .cancel-button {\r\n");
          out.write("                \tmargin-left: 10px;\r\n");
          out.write("                    background-color: #e74c3c; /* Default background color */\r\n");
          out.write("                }\r\n");
          out.write("\r\n");
          out.write("                .cancel-button:hover {\r\n");
          out.write("                    background-color: #c0392b; /* Hover background color */\r\n");
          out.write("                }\r\n");
          out.write("\r\n");
          out.write("                /* Add style to the table */\r\n");
          out.write("                table {\r\n");
          out.write("                    width: 100%;\r\n");
          out.write("                    border-collapse: collapse;\r\n");
          out.write("                    margin-top: 20px;\r\n");
          out.write("                }\r\n");
          out.write("\r\n");
          out.write("                th, td {\r\n");
          out.write("                    padding: 15px;\r\n");
          out.write("                    border: none; /* Remove borders */\r\n");
          out.write("                    text-align: left;\r\n");
          out.write("                    white-space: nowrap; /* Prevent text wrapping */\r\n");
          out.write("                }\r\n");
          out.write("\r\n");
          out.write("                th {\r\n");
          out.write("                    color: #4CAF50;\r\n");
          out.write("                }\r\n");
          out.write("\r\n");
          out.write("                tr:nth-child(even) {\r\n");
          out.write("                    background-color: transparent;\r\n");
          out.write("                }\r\n");
          out.write("\r\n");
          out.write("                .button-container {\r\n");
          out.write("                    display: flex;\r\n");
          out.write("                    justify-content: center;\r\n");
          out.write("                    padding: 10px;\r\n");
          out.write("                    align-items: center;\r\n");
          out.write("                    margin-top: 15px;\r\n");
          out.write("                }\r\n");
          out.write("                \r\n");
          out.write("                .sucess-box {\r\n");
          out.write("\tdisplay: none;\r\n");
          out.write("\tbackground-color: #4CAF50;\r\n");
          out.write("  padding: 1px;\r\n");
          out.write("  margin-bottom: 40px;\r\n");
          out.write("}\r\n");
          out.write("\r\n");
          out.write("/* Style for the close button */\r\n");
          out.write(".close-button {\r\n");
          out.write("  position: relative;\r\n");
          out.write("    top: -34px;\r\n");
          out.write("    right: 16px;\r\n");
          out.write("    color: black;\r\n");
          out.write("    cursor: pointer;\r\n");
          out.write("    float: right;\r\n");
          out.write("}\r\n");
          out.write("            </style>\r\n");
          out.write("        </head>\r\n");
          out.write("        <body>\r\n");
          out.write("        \t");
          if (_jspx_meth_h_005finputText_005f0(_jspx_th_f_005fview_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("<div Class=\"sucess-box\" id=\"manageBox\">\r\n");
          out.write("    ");
          if (_jspx_meth_h_005fmessages_005f0(_jspx_th_f_005fview_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("    <span class=\"close-button\" onclick=\"closeMessage()\">X</span>\r\n");
          out.write("</div>\r\n");
          out.write("\r\n");
          out.write("<h2>\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_h_005foutputText_005f0(_jspx_th_f_005fview_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t</h2>\r\n");
          out.write("\r\n");
          out.write("            ");
          if (_jspx_meth_h_005fform_005f0(_jspx_th_f_005fview_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            \r\n");
          out.write("            \t<script>\r\n");
          out.write("    // JavaScript function to close the message box\r\n");
          out.write("  viewMsg();\r\n");
          out.write("  function viewMsg() {\r\n");
          out.write("    var manageBox = document.getElementById('manageBox');\r\n");
          out.write("    var errorBox = document.getElementById('errorBox');\r\n");
          out.write("    var sucessInput = document.getElementById('sucessInput');\r\n");
          out.write("        \r\n");
          out.write("    if(sucessInput.value === 'confirmed'){\r\n");
          out.write("    \tmanageBox.style.display = 'block';\r\n");
          out.write("        }\r\n");
          out.write("    else if(sucessInput.value === 'canceled'){\r\n");
          out.write("    \tmanageBox.style.display = 'block';\r\n");
          out.write("    \tmanageBox.style.backgroundColor = \"red\";   \r\n");
          out.write("        }\r\n");
          out.write("    else{\r\n");
          out.write("    \tmanageBox.style.display = 'none';\r\n");
          out.write("        }\r\n");
          out.write("\r\n");
          out.write("    \r\n");
          out.write("}\r\n");
          out.write("    \r\n");
          out.write("    function closeMessage() {\r\n");
          out.write("   \t  \tvar manageBox = document.getElementById('manageBox');\r\n");
          out.write("\t    manageBox.style.display = 'none';\r\n");
          out.write("    }\r\n");
          out.write("\r\n");
          out.write("  </script>\r\n");
          out.write("            \r\n");
          out.write("        </body>\r\n");
          out.write("    </html>\r\n");
          int evalDoAfterBody = _jspx_th_f_005fview_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_f_005fview_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005fview_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005finputText_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fview_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:inputText
    com.sun.faces.taglib.html_basic.InputTextTag _jspx_th_h_005finputText_005f0 = new com.sun.faces.taglib.html_basic.InputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005finputText_005f0);
    try {
      _jspx_th_h_005finputText_005f0.setPageContext(_jspx_page_context);
      _jspx_th_h_005finputText_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fview_005f0);
      // /AppointmentDetails.jsp(126,9) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005finputText_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/AppointmentDetails.jsp(126,9) '#{manageMsg}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{manageMsg}",java.lang.Object.class)));
      // /AppointmentDetails.jsp(126,9) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_h_005finputText_005f0.setId("sucessInput");
      // /AppointmentDetails.jsp(126,9) name = style type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005finputText_005f0.setStyle(new org.apache.jasper.el.JspValueExpression("/AppointmentDetails.jsp(126,9) 'display: none;'",_jsp_getExpressionFactory().createValueExpression("display: none;",java.lang.String.class)));
      _jspx_th_h_005finputText_005f0.setJspId("jsp_813251680_1");
      int _jspx_eval_h_005finputText_005f0 = _jspx_th_h_005finputText_005f0.doStartTag();
      if (_jspx_th_h_005finputText_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005finputText_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fmessages_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fview_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:messages
    com.sun.faces.taglib.html_basic.MessagesTag _jspx_th_h_005fmessages_005f0 = new com.sun.faces.taglib.html_basic.MessagesTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fmessages_005f0);
    try {
      _jspx_th_h_005fmessages_005f0.setPageContext(_jspx_page_context);
      _jspx_th_h_005fmessages_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fview_005f0);
      // /AppointmentDetails.jsp(128,4) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_h_005fmessages_005f0.setId("manageMsg");
      _jspx_th_h_005fmessages_005f0.setJspId("jsp_813251680_2");
      int _jspx_eval_h_005fmessages_005f0 = _jspx_th_h_005fmessages_005f0.doStartTag();
      if (_jspx_th_h_005fmessages_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fmessages_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fview_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f0 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f0);
    try {
      _jspx_th_h_005foutputText_005f0.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fview_005f0);
      // /AppointmentDetails.jsp(133,3) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/AppointmentDetails.jsp(133,3) 'Manage Appointment'",_jsp_getExpressionFactory().createValueExpression("Manage Appointment",java.lang.Object.class)));
      _jspx_th_h_005foutputText_005f0.setJspId("jsp_813251680_3");
      int _jspx_eval_h_005foutputText_005f0 = _jspx_th_h_005foutputText_005f0.doStartTag();
      if (_jspx_th_h_005foutputText_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fform_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fview_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:form
    com.sun.faces.taglib.html_basic.FormTag _jspx_th_h_005fform_005f0 = new com.sun.faces.taglib.html_basic.FormTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fform_005f0);
    try {
      _jspx_th_h_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_h_005fform_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fview_005f0);
      // /AppointmentDetails.jsp(136,12) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005fform_005f0.setStyleClass(new org.apache.jasper.el.JspValueExpression("/AppointmentDetails.jsp(136,12) 'form-container'",_jsp_getExpressionFactory().createValueExpression("form-container",java.lang.String.class)));
      _jspx_th_h_005fform_005f0.setJspId("jsp_813251680_4");
      int _jspx_eval_h_005fform_005f0 = _jspx_th_h_005fform_005f0.doStartTag();
      if (_jspx_eval_h_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_h_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_h_005fform_005f0);
        }
        do {
          out.write("\r\n");
          out.write("                <table>\r\n");
          out.write("                    <tr>\r\n");
          out.write("                        <th>Appointment Id:</th>\r\n");
          out.write("                        <td>");
          if (_jspx_meth_h_005foutputText_005f1(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("</td>\r\n");
          out.write("                        <th>Name :</th>\r\n");
          out.write("                        <td>");
          if (_jspx_meth_h_005foutputText_005f2(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("</td>\r\n");
          out.write("                    </tr>\r\n");
          out.write("\r\n");
          out.write("                    <tr>\r\n");
          out.write("                        <th>Dob:</th>\r\n");
          out.write("                        <td>");
          if (_jspx_meth_h_005foutputText_005f3(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("</td>\r\n");
          out.write("                        <th>Gender:</th>\r\n");
          out.write("                        <td>");
          if (_jspx_meth_h_005foutputText_005f4(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("</td>\r\n");
          out.write("                    </tr>\r\n");
          out.write("\r\n");
          out.write("                    <tr>\r\n");
          out.write("                        <th><span class=\"form-label\">Appointment Date:</span></th>\r\n");
          out.write("                        <td>");
          if (_jspx_meth_h_005foutputText_005f5(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("</td>\r\n");
          out.write("                        <th><span class=\"form-label\">Appointment Time:</span></th>\r\n");
          out.write("                        <td>");
          if (_jspx_meth_h_005foutputText_005f6(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("</td>\r\n");
          out.write("                    </tr>\r\n");
          out.write("                </table>\r\n");
          out.write("\r\n");
          out.write("                <div class=\"button-container\">\r\n");
          out.write("                    ");
          if (_jspx_meth_h_005fcommandButton_005f0(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_h_005fcommandButton_005f1(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_h_005fcommandButton_005f2(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                </div>\r\n");
          out.write("\r\n");
          out.write("                <br />\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_h_005fform_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_h_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_h_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fform_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f1 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f1);
    try {
      _jspx_th_h_005foutputText_005f1.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /AppointmentDetails.jsp(140,28) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/AppointmentDetails.jsp(140,28) '#{appointmentDetail.uhid}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{appointmentDetail.uhid}",java.lang.Object.class)));
      // /AppointmentDetails.jsp(140,28) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f1.setStyleClass(new org.apache.jasper.el.JspValueExpression("/AppointmentDetails.jsp(140,28) 'form-input'",_jsp_getExpressionFactory().createValueExpression("form-input",java.lang.String.class)));
      _jspx_th_h_005foutputText_005f1.setJspId("jsp_813251680_5");
      int _jspx_eval_h_005foutputText_005f1 = _jspx_th_h_005foutputText_005f1.doStartTag();
      if (_jspx_th_h_005foutputText_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f1, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f2 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f2);
    try {
      _jspx_th_h_005foutputText_005f2.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /AppointmentDetails.jsp(142,28) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/AppointmentDetails.jsp(142,28) '#{appointmentDetail.firstName} #{appointmentDetail.lastName}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{appointmentDetail.firstName} #{appointmentDetail.lastName}",java.lang.Object.class)));
      // /AppointmentDetails.jsp(142,28) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f2.setStyleClass(new org.apache.jasper.el.JspValueExpression("/AppointmentDetails.jsp(142,28) 'form-input'",_jsp_getExpressionFactory().createValueExpression("form-input",java.lang.String.class)));
      _jspx_th_h_005foutputText_005f2.setJspId("jsp_813251680_6");
      int _jspx_eval_h_005foutputText_005f2 = _jspx_th_h_005foutputText_005f2.doStartTag();
      if (_jspx_th_h_005foutputText_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f2, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f3 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f3);
    try {
      _jspx_th_h_005foutputText_005f3.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /AppointmentDetails.jsp(147,28) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f3.setValue(new org.apache.jasper.el.JspValueExpression("/AppointmentDetails.jsp(147,28) '#{enrollmentFound.dob.toString().substring(0,10)}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{enrollmentFound.dob.toString().substring(0,10)}",java.lang.Object.class)));
      // /AppointmentDetails.jsp(147,28) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f3.setStyleClass(new org.apache.jasper.el.JspValueExpression("/AppointmentDetails.jsp(147,28) 'form-input'",_jsp_getExpressionFactory().createValueExpression("form-input",java.lang.String.class)));
      _jspx_th_h_005foutputText_005f3.setJspId("jsp_813251680_7");
      int _jspx_eval_h_005foutputText_005f3 = _jspx_th_h_005foutputText_005f3.doStartTag();
      if (_jspx_th_h_005foutputText_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f3, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f4 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f4);
    try {
      _jspx_th_h_005foutputText_005f4.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /AppointmentDetails.jsp(149,28) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f4.setValue(new org.apache.jasper.el.JspValueExpression("/AppointmentDetails.jsp(149,28) '#{enrollmentFound.gender}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{enrollmentFound.gender}",java.lang.Object.class)));
      // /AppointmentDetails.jsp(149,28) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f4.setStyleClass(new org.apache.jasper.el.JspValueExpression("/AppointmentDetails.jsp(149,28) 'form-input'",_jsp_getExpressionFactory().createValueExpression("form-input",java.lang.String.class)));
      _jspx_th_h_005foutputText_005f4.setJspId("jsp_813251680_8");
      int _jspx_eval_h_005foutputText_005f4 = _jspx_th_h_005foutputText_005f4.doStartTag();
      if (_jspx_th_h_005foutputText_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f4, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f5 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f5);
    try {
      _jspx_th_h_005foutputText_005f5.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /AppointmentDetails.jsp(154,28) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f5.setValue(new org.apache.jasper.el.JspValueExpression("/AppointmentDetails.jsp(154,28) '#{appointmentDetail.appointmentDate.toString().substring(0,10)}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{appointmentDetail.appointmentDate.toString().substring(0,10)}",java.lang.Object.class)));
      // /AppointmentDetails.jsp(154,28) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f5.setStyleClass(new org.apache.jasper.el.JspValueExpression("/AppointmentDetails.jsp(154,28) 'form-input'",_jsp_getExpressionFactory().createValueExpression("form-input",java.lang.String.class)));
      _jspx_th_h_005foutputText_005f5.setJspId("jsp_813251680_9");
      int _jspx_eval_h_005foutputText_005f5 = _jspx_th_h_005foutputText_005f5.doStartTag();
      if (_jspx_th_h_005foutputText_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f5, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f6 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f6);
    try {
      _jspx_th_h_005foutputText_005f6.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /AppointmentDetails.jsp(156,28) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f6.setValue(new org.apache.jasper.el.JspValueExpression("/AppointmentDetails.jsp(156,28) '#{appointmentDetail.appointmentTime}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{appointmentDetail.appointmentTime}",java.lang.Object.class)));
      // /AppointmentDetails.jsp(156,28) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f6.setStyleClass(new org.apache.jasper.el.JspValueExpression("/AppointmentDetails.jsp(156,28) 'form-input'",_jsp_getExpressionFactory().createValueExpression("form-input",java.lang.String.class)));
      _jspx_th_h_005foutputText_005f6.setJspId("jsp_813251680_10");
      int _jspx_eval_h_005foutputText_005f6 = _jspx_th_h_005foutputText_005f6.doStartTag();
      if (_jspx_th_h_005foutputText_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f6, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fcommandButton_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:commandButton
    com.sun.faces.taglib.html_basic.CommandButtonTag _jspx_th_h_005fcommandButton_005f0 = new com.sun.faces.taglib.html_basic.CommandButtonTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fcommandButton_005f0);
    try {
      _jspx_th_h_005fcommandButton_005f0.setPageContext(_jspx_page_context);
      _jspx_th_h_005fcommandButton_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /AppointmentDetails.jsp(161,20) name = action type = javax.el.MethodExpression reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = true methodSignature = java.lang.Object action()
      _jspx_th_h_005fcommandButton_005f0.setAction(new org.apache.jasper.el.JspMethodExpression("/AppointmentDetails.jsp(161,20) '#{appointmentImpl.goBackToViewAppointments()}'",_jsp_getExpressionFactory().createMethodExpression(_jspx_page_context.getELContext(),"#{appointmentImpl.goBackToViewAppointments()}",java.lang.Object.class,new java.lang.Class[] {})));
      // /AppointmentDetails.jsp(161,20) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005fcommandButton_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/AppointmentDetails.jsp(161,20) 'Go Back'",_jsp_getExpressionFactory().createValueExpression("Go Back",java.lang.Object.class)));
      // /AppointmentDetails.jsp(161,20) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005fcommandButton_005f0.setStyleClass(new org.apache.jasper.el.JspValueExpression("/AppointmentDetails.jsp(161,20) 'custom-button go-back-button'",_jsp_getExpressionFactory().createValueExpression("custom-button go-back-button",java.lang.String.class)));
      _jspx_th_h_005fcommandButton_005f0.setJspId("jsp_813251680_11");
      int _jspx_eval_h_005fcommandButton_005f0 = _jspx_th_h_005fcommandButton_005f0.doStartTag();
      if (_jspx_th_h_005fcommandButton_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fcommandButton_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fcommandButton_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:commandButton
    com.sun.faces.taglib.html_basic.CommandButtonTag _jspx_th_h_005fcommandButton_005f1 = new com.sun.faces.taglib.html_basic.CommandButtonTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fcommandButton_005f1);
    try {
      _jspx_th_h_005fcommandButton_005f1.setPageContext(_jspx_page_context);
      _jspx_th_h_005fcommandButton_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /AppointmentDetails.jsp(162,20) name = action type = javax.el.MethodExpression reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = true methodSignature = java.lang.Object action()
      _jspx_th_h_005fcommandButton_005f1.setAction(new org.apache.jasper.el.JspMethodExpression("/AppointmentDetails.jsp(162,20) '#{appointmentImpl.confirmAppointment(appointmentDetail.appointmentId)}'",_jsp_getExpressionFactory().createMethodExpression(_jspx_page_context.getELContext(),"#{appointmentImpl.confirmAppointment(appointmentDetail.appointmentId)}",java.lang.Object.class,new java.lang.Class[] {})));
      // /AppointmentDetails.jsp(162,20) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005fcommandButton_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/AppointmentDetails.jsp(162,20) 'Confirm'",_jsp_getExpressionFactory().createValueExpression("Confirm",java.lang.Object.class)));
      // /AppointmentDetails.jsp(162,20) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005fcommandButton_005f1.setStyleClass(new org.apache.jasper.el.JspValueExpression("/AppointmentDetails.jsp(162,20) 'custom-button confirm-button'",_jsp_getExpressionFactory().createValueExpression("custom-button confirm-button",java.lang.String.class)));
      _jspx_th_h_005fcommandButton_005f1.setJspId("jsp_813251680_12");
      int _jspx_eval_h_005fcommandButton_005f1 = _jspx_th_h_005fcommandButton_005f1.doStartTag();
      if (_jspx_th_h_005fcommandButton_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fcommandButton_005f1, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fcommandButton_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:commandButton
    com.sun.faces.taglib.html_basic.CommandButtonTag _jspx_th_h_005fcommandButton_005f2 = new com.sun.faces.taglib.html_basic.CommandButtonTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fcommandButton_005f2);
    try {
      _jspx_th_h_005fcommandButton_005f2.setPageContext(_jspx_page_context);
      _jspx_th_h_005fcommandButton_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /AppointmentDetails.jsp(163,20) name = action type = javax.el.MethodExpression reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = true methodSignature = java.lang.Object action()
      _jspx_th_h_005fcommandButton_005f2.setAction(new org.apache.jasper.el.JspMethodExpression("/AppointmentDetails.jsp(163,20) '#{appointmentImpl.cancelAppointment(appointmentDetail.appointmentId)}'",_jsp_getExpressionFactory().createMethodExpression(_jspx_page_context.getELContext(),"#{appointmentImpl.cancelAppointment(appointmentDetail.appointmentId)}",java.lang.Object.class,new java.lang.Class[] {})));
      // /AppointmentDetails.jsp(163,20) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005fcommandButton_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/AppointmentDetails.jsp(163,20) 'Cancel'",_jsp_getExpressionFactory().createValueExpression("Cancel",java.lang.Object.class)));
      // /AppointmentDetails.jsp(163,20) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005fcommandButton_005f2.setStyleClass(new org.apache.jasper.el.JspValueExpression("/AppointmentDetails.jsp(163,20) 'custom-button cancel-button'",_jsp_getExpressionFactory().createValueExpression("custom-button cancel-button",java.lang.String.class)));
      _jspx_th_h_005fcommandButton_005f2.setJspId("jsp_813251680_13");
      int _jspx_eval_h_005fcommandButton_005f2 = _jspx_th_h_005fcommandButton_005f2.doStartTag();
      if (_jspx_th_h_005fcommandButton_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fcommandButton_005f2, _jsp_getInstanceManager(), false);
    }
    return false;
  }
}
