package com.java.BankWebsite;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.SQLException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

/**
 * Servlet implementation class ShowServlet
 */
public class ShowServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public ShowServlet() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        response.setContentType("text/html");
        PrintWriter out = response.getWriter();
        BankDAOimpl impl = new BankDAOimpl();
        BankDAO dao = new BankDAOimpl();
        HttpSession session = request.getSession(true);
        int accno = (Integer) session.getAttribute("accno");

        try {
            out.println("<html>");
            out.println("<head>");
            out.println("<style>");
            out.println("body { font-family: Arial, sans-serif; background-color: #f5f5f5; margin: 0; padding: 0; margin-top: 40px; }");
            out.println("center { display: flex; flex-direction: column; justify-content: center; align-items: center; height: 5vh; }"); // Adjusted height
            out.println("h1 { font-size: 36px; color: #007BFF; margin: 10px 0; }"); // Reduced margin
            out.println("h3 { font-size: 30px; color: #007BFF; margin: 10px 0; margin-top: 40px;}");
            out.println("p { font-size: 20px; margin: 5px 0; margin-top: 60px;}"); // Reduced margin
            out.println("</style>");
            out.println("</head>");
            out.println("<body>");

            // Output the content generated by your servlet
            out.println("<center><h1>INFINITE BANK</h1></center>");
            out.println("<center><h3>Account Details</h3></center>");
            List<Bank> accountlist = dao.showAccountDetailsDao(accno);
            for (Bank bank : accountlist) {
                out.println("<center><p>Account Number is : " + bank.getAccountNo() + "</p></center>");
                out.println("<center><p>Name : " + bank.getFirstName() + " " + bank.getLastName() + "</p></center>");
                out.println("<center><p>City : " + bank.getCity() + "</p></center>");
                out.println("<center><p>State : " + bank.getState() + "</p></center>");
                out.println("<center><p>CheqFacil : " + bank.getCheqFacil() + "</p></center>");
                out.println("<center><p>DateOfOpen : " + bank.getDateOfOpen() + "</p></center>");
            }

            out.println("</body>");
            out.println("</html>");

        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }



	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}
